### ISSUE TITLE
Making mules with Golden Apple will fail

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/MobLimiter#26]
Donkeys and Horses via Golden Apple → The mule foal will grow and when it enters adulthood… will vanish.

When Golden Carrot is used, there is no such problem.

**Comment by eliadil** [comment]
Whats the status on this one? I think someone was testing something about it?

**Comment by matejdro** [comment]
Both me and riddle tried it and could not reproduce so I think it is not a bug (his mule probably just wandered off or something).

**Comment by eliadil** [comment]
Sweet.
